### ISSUE TITLE
Set the default snapshot resolution to VGA

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-capture-android#16]
I did some testing using my phone (Nexus 5) as the Evercam Capture camera and I've noticed that most of the snapshots were either taking a long time (5, 8, 12 seconds) or timing out. When I changed the resolution to 640x480 there was a dramatic improvement in the speed of response and barely any of the requests timed out.

It seems sensible to make that the default?

@liutingdu @marcoherbst

**Comment by marcoherbst** [comment]
+1

**Comment by liutingdu** [comment]
@mosic Good point :) Thanks!
