### ISSUE TITLE
App crashes while reading network location

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-capture-android#7]
Thanks @ephe-meral for spotting this one.
M

**Comment by liutingdu** [comment]
We are not using Google Play Service's location API, but it's still necessary to make sure the app works without Google Play Service, create a separate issue #8 for that. This issue will be only about fixing the crash while fetching location.

**Comment by liutingdu** [comment]
Should be fixed in 74939fb0a4d3bc3850dab6814d52a074e717d2b0, but need more testing
